version: '3.7'

services:
  proxy:
    image: traefik
    command: --api \
      --docker \
      --docker.swarmmode \
      --docker.watch \
      --logLevel=DEBUG
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.toml:/traefik.toml'
      - 'proxy-data:/data'

  app:
    image: registry.gitlab.com/blasttheory/gift/gift-app:latest-production
    volumes:
      - './nginx-app.conf:/etc/nginx/nginx.conf'
    deploy:
      replicas: 2
      labels:
        - 'traefik.enable=true'
        - 'traefik.port=80'
        - 'traefik.domain=thegift.app'
        - 'traefik.frontend.rule=Host:thegift.app'

  api:
    image: registry.gitlab.com/blasttheory/gift/gift-api:latest
    environment:
      ENVIRONMENT: 'production'
      DEBUG: '(INFO|WARN|ERROR):*'
      SQL_URI: 'postgresql://gift:gift@db/gift'
      CORS_ALLOWED_ORIGINS: 'https://thegift.app'
      AWS_BUCKET: 'bt-gift'
      AWS_REGION: 'eu-west-2'
    deploy:
      replicas: 2
      labels:
        - 'traefik.enable=true'
        - 'traefik.port=5000'
        - 'traefik.domain=api.thegift.app'
        - 'traefik.frontend.rule=Host:api.thegift.app'

volumes:
   proxy-data:
